/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17798 2009-10-27 06:44:54Z magfr $
 */
#ifndef SEMSSTATS_H
#define SEMSSTATS_H

/* function declarations */
void init_semsStats(void);
Netsnmp_Node_Handler handle_semsStatsCallsAvg;
Netsnmp_Node_Handler handle_semsStatsCallsMax;
Netsnmp_Node_Handler handle_semsStatsCpsAvg;
Netsnmp_Node_Handler handle_semsStatsCpsMax;

#endif /* SEMSSTATS_H */
