/*
 * Internal module API header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Sep  8 11:08:26 2006
 */

#ifndef _py_ivrAPI_H
#define	_py_ivrAPI_H


#include <sip.h>


/*
 * Convenient names to refer to the names of classes defined in this module.
 * These are part of the public API.
 */

#define	sipName_IvrDialog	sipNm_py_ivr_IvrDialog
#define	sipName_AmSipDialog	sipNm_py_ivr_AmSipDialog
#define	sipName_AmSipReply	sipNm_py_ivr_AmSipReply
#define	sipName_AmSipRequest	sipNm_py_ivr_AmSipRequest


/* Convenient names to call the SIP API. */
#define	sipConvertFromSliceObject(o,len,start,stop,step,slen)	PySlice_GetIndicesEx((PySliceObject *)(o),(len),(start),(stop),(step),(slen))
#define	sipIsSubClassInstance(o,wt)	PyObject_TypeCheck((o),(PyTypeObject *)(wt))

#define	sipMapStringToClass		sipAPI_py_ivr -> api_map_string_to_class
#define	sipMapIntToClass		sipAPI_py_ivr -> api_map_int_to_class
#define	sipMalloc			sipAPI_py_ivr -> api_malloc
#define	sipFree				sipAPI_py_ivr -> api_free
#define	sipBuildResult			sipAPI_py_ivr -> api_build_result
#define	sipCallMethod			sipAPI_py_ivr -> api_call_method
#define	sipParseResult			sipAPI_py_ivr -> api_parse_result
#define	sipParseArgs			sipAPI_py_ivr -> api_parse_args
#define	sipCommonCtor			sipAPI_py_ivr -> api_common_ctor
#define	sipCommonDtor			sipAPI_py_ivr -> api_common_dtor
#define	sipConvertFromSequenceIndex	sipAPI_py_ivr -> api_convert_from_sequence_index
#define	sipConvertFromVoidPtr		sipAPI_py_ivr -> api_convert_from_void_ptr
#define	sipConvertToCpp			sipAPI_py_ivr -> api_convert_to_cpp
#define	sipConvertToVoidPtr		sipAPI_py_ivr -> api_convert_to_void_ptr
#define	sipNoCtor			sipAPI_py_ivr -> api_no_ctor
#define	sipNoFunction			sipAPI_py_ivr -> api_no_function
#define	sipNoMethod			sipAPI_py_ivr -> api_no_method
#define	sipBadClass			sipAPI_py_ivr -> api_bad_class
#define	sipBadSetType			sipAPI_py_ivr -> api_bad_set_type
#define	sipBadCatcherResult		sipAPI_py_ivr -> api_bad_catcher_result
#define	sipTrace			sipAPI_py_ivr -> api_trace
#define	sipTransfer			sipAPI_py_ivr -> api_transfer
#define	sipGetWrapper			sipAPI_py_ivr -> api_get_wrapper
#define	sipGetCppPtr			sipAPI_py_ivr -> api_get_cpp_ptr
#define	sipGetComplexCppPtr		sipAPI_py_ivr -> api_get_complex_cpp_ptr
#define	sipIsPyMethod			sipAPI_py_ivr -> api_is_py_method
#define	sipMapCppToSelf			sipAPI_py_ivr -> api_map_cpp_to_self
#define	sipMapCppToSelfSubClass		sipAPI_py_ivr -> api_map_cpp_to_self_sub_class
#define	sipNewCppToSelf			sipAPI_py_ivr -> api_new_cpp_to_self
#define	sipNewCppToSelfSubClass		sipAPI_py_ivr -> api_new_cpp_to_self_sub_class
#define	sipCallHook			sipAPI_py_ivr -> api_call_hook
#define	sipStartThread			sipAPI_py_ivr -> api_start_thread
#define	sipEndThread			sipAPI_py_ivr -> api_end_thread
#define	sipEmitSignal			sipAPI_py_ivr -> api_emit_signal
#define	sipEmitToSlot			sipAPI_py_ivr -> api_emit_to_slot
#define	sipConnectRx			sipAPI_py_ivr -> api_connect_rx
#define	sipDisconnectRx			sipAPI_py_ivr -> api_disconnect_rx
#define	sipGetSender			sipAPI_py_ivr -> api_get_sender
#define	sipRaiseUnknownException	sipAPI_py_ivr -> api_raise_unknown_exception
#define	sipRaiseClassException		sipAPI_py_ivr -> api_raise_class_exception
#define	sipRaiseSubClassException	sipAPI_py_ivr -> api_raise_sub_class_exception
#define	sipBadLengthForSlice		sipAPI_py_ivr -> api_bad_length_for_slice
#define	sipClassName			sipAPI_py_ivr -> api_class_name
#define	sipAddClassInstance		sipAPI_py_ivr -> api_add_class_instance


/* The strings used by this module. */
extern char sipNm_py_ivr_onOtherReply[];
extern char sipNm_py_ivr_onOtherBye[];
extern char sipNm_py_ivr_onDtmf[];
extern char sipNm_py_ivr_onCancel[];
extern char sipNm_py_ivr_onBye[];
extern char sipNm_py_ivr_onSessionStart[];
extern char sipNm_py_ivr_onInvite[];
extern char sipNm_py_ivr_setStopped[];
extern char sipNm_py_ivr_acceptAudio[];
extern char sipNm_py_ivr_dlg[];
extern char sipNm_py_ivr_IvrDialog[];
extern char sipNm_py_ivr_reinvite[];
extern char sipNm_py_ivr_update[];
extern char sipNm_py_ivr_cancel[];
extern char sipNm_py_ivr_bye[];
extern char sipNm_py_ivr_sendRequest[];
extern char sipNm_py_ivr_reply[];
extern char sipNm_py_ivr_updateStatus[];
extern char sipNm_py_ivr_getContactHdr[];
extern char sipNm_py_ivr_getStatus[];
extern char sipNm_py_ivr_getUACTransPending[];
extern char sipNm_py_ivr_setRoute[];
extern char sipNm_py_ivr_getRoute[];
extern char sipNm_py_ivr_local_party[];
extern char sipNm_py_ivr_remote_party[];
extern char sipNm_py_ivr_contact_uri[];
extern char sipNm_py_ivr_remote_uri[];
extern char sipNm_py_ivr_local_uri[];
extern char sipNm_py_ivr_sip_port[];
extern char sipNm_py_ivr_sip_ip[];
extern char sipNm_py_ivr_Disconnecting[];
extern char sipNm_py_ivr_Connected[];
extern char sipNm_py_ivr_Pending[];
extern char sipNm_py_ivr_Disconnected[];
extern char sipNm_py_ivr_AmSipDialog[];
extern char sipNm_py_ivr_local_tag[];
extern char sipNm_py_ivr_remote_tag[];
extern char sipNm_py_ivr_next_request_uri[];
extern char sipNm_py_ivr_reason[];
extern char sipNm_py_ivr_code[];
extern char sipNm_py_ivr_AmSipReply[];
extern char sipNm_py_ivr_getHeader[];
extern char sipNm_py_ivr_key[];
extern char sipNm_py_ivr_next_hop[];
extern char sipNm_py_ivr_route[];
extern char sipNm_py_ivr_body[];
extern char sipNm_py_ivr_hdrs[];
extern char sipNm_py_ivr_cseq[];
extern char sipNm_py_ivr_to_tag[];
extern char sipNm_py_ivr_from_tag[];
extern char sipNm_py_ivr_callid[];
extern char sipNm_py_ivr_to[];
extern char sipNm_py_ivr_from[];
extern char sipNm_py_ivr_from_uri[];
extern char sipNm_py_ivr_r_uri[];
extern char sipNm_py_ivr_port[];
extern char sipNm_py_ivr_dstip[];
extern char sipNm_py_ivr_domain[];
extern char sipNm_py_ivr_user[];
extern char sipNm_py_ivr_method[];
extern char sipNm_py_ivr_cmd[];
extern char sipNm_py_ivr_AmSipRequest[];
extern char sipNm_py_ivr_string[];


/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_py_ivr;
extern sipExportedModuleDef sipModuleAPI_py_ivr;

#endif
