/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Sep  8 11:08:26 2006
 */

#ifndef _py_ivrAmSipReply_h
#define	_py_ivrAmSipReply_h

#line 6 "AmSipReply.sip"
#include "../../../core/AmSipReply.h"
#line 13 "sippy_ivrAmSipReply.h"

#include "sippy_ivrstring.h"


#define	sipClass_AmSipReply	sipModuleAPI_py_ivr.em_types[2]
#define	sipCast_AmSipReply	sipType_AmSipReply.td_cast
#define	sipForceConvertTo_AmSipReply	sipType_AmSipReply.td_fcto

extern sipTypeDef sipType_AmSipReply;

#endif
