/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Sep  8 11:08:26 2006
 */

#ifndef _py_ivrIvrDialog_h
#define	_py_ivrIvrDialog_h

#line 6 "IvrDialog.sip"
#include "../Ivr.h"
#line 13 "sippy_ivrIvrDialog.h"

#include "sippy_ivrAmSipDialog.h"
#include "sippy_ivrAmSipReply.h"
#include "sippy_ivrAmSipRequest.h"
#include "sippy_ivrstring.h"


#define	sipClass_IvrDialog	sipModuleAPI_py_ivr.em_types[0]
#define	sipCast_IvrDialog	sipType_IvrDialog.td_cast
#define	sipForceConvertTo_IvrDialog	sipType_IvrDialog.td_fcto

extern sipTypeDef sipType_IvrDialog;


class sipIvrDialog : public IvrDialog
{
public:
	sipIvrDialog();
	virtual ~sipIvrDialog();

	/*
	 * There is a public method for every virtual method visible from
	 * this class.
	 */
	void onInvite(const AmSipRequest&);
	void onSessionStart(const AmSipRequest&);
	void onBye(const AmSipRequest&);
	void onCancel();
	void onDtmf(int,int);
	void onOtherBye(const AmSipRequest&);
	void onOtherReply(const AmSipReply&);

	sipWrapper *sipPySelf;

private:
	sipIvrDialog(const sipIvrDialog &);
	sipIvrDialog &operator = (const sipIvrDialog &);

	sipMethodCache sipPyMethods[7];
};

#endif
