/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Sep  8 11:08:26 2006
 */

#ifndef _py_ivrAmSipDialog_h
#define	_py_ivrAmSipDialog_h

#line 6 "AmSipDialog.sip"
#include "../../../core/AmSipDialog.h"
#line 13 "sippy_ivrAmSipDialog.h"

#include "sippy_ivrstring.h"
#include "sippy_ivrAmSipRequest.h"
#include "sippy_ivrAmSipReply.h"


#define	sipClass_AmSipDialog	sipModuleAPI_py_ivr.em_types[1]
#define	sipCast_AmSipDialog	sipType_AmSipDialog.td_cast
#define	sipForceConvertTo_AmSipDialog	sipType_AmSipDialog.td_fcto

extern sipTypeDef sipType_AmSipDialog;

#endif
