/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Sep  8 11:08:26 2006
 */

#ifndef _py_ivrstring_h
#define	_py_ivrstring_h



#line 4 "string.sip"
#include <string>
using std::string;
#line 16 "sippy_ivrstring.h"


#define	sipForceConvertTo_string	sipMappedType_string.mt_fcto
#define	sipConvertTo_string	sipMappedType_string.mt_cto
#define	sipConvertFrom_string	sipMappedType_string.mt_cfrom

extern sipMappedTypeDef sipMappedType_string;

#endif
