/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Sep  8 11:08:26 2006
 */

#ifndef _py_ivrAmSipRequest_h
#define	_py_ivrAmSipRequest_h

#line 6 "AmSipRequest.sip"
#include "../../../core/AmSipRequest.h"
#line 13 "sippy_ivrAmSipRequest.h"

#include "sippy_ivrstring.h"


#define	sipClass_AmSipRequest	sipModuleAPI_py_ivr.em_types[3]
#define	sipCast_AmSipRequest	sipType_AmSipRequest.td_cast
#define	sipForceConvertTo_AmSipRequest	sipType_AmSipRequest.td_fcto

extern sipTypeDef sipType_AmSipRequest;

#endif
