/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:04:41 2007
 */

#ifndef _py_semsIvrDialog_h
#define	_py_semsIvrDialog_h

#line 6 "IvrDialog.sip"
#include "../Ivr.h"
#line 13 "sippy_semsIvrDialog.h"

#include "sippy_semsAmSipDialog.h"
#include "sippy_semsAmSipReply.h"
#include "sippy_semsAmSipRequest.h"
#include "sippy_semsstring.h"


#define	sipClass_IvrDialog	sipModuleAPI_py_sems.em_types[0]
#define	sipCast_IvrDialog	sipType_IvrDialog.td_cast
#define	sipForceConvertTo_IvrDialog	sipType_IvrDialog.td_fcto

extern sipTypeDef sipType_IvrDialog;


class sipIvrDialog : public IvrDialog
{
public:
	sipIvrDialog();
	virtual ~sipIvrDialog();

	/*
	 * There is a public method for every virtual method visible from
	 * this class.
	 */
	void onInvite(const AmSipRequest&);
	void onSessionStart(const AmSipRequest&);
	void onBye(const AmSipRequest&);
	void onCancel();
	void onDtmf(int,int);
	void onOtherBye(const AmSipRequest&);
	void onOtherReply(const AmSipReply&);

	sipWrapper *sipPySelf;

private:
	sipIvrDialog(const sipIvrDialog &);
	sipIvrDialog &operator = (const sipIvrDialog &);

	sipMethodCache sipPyMethods[7];
};

#endif
